import { writeFileSync } from "fs";
import { basename } from "path";

// ═══════════════════════════════════════════════════════════════════
// DIAGRAM GENERATOR — Produces Gravity-styled HTML architecture maps
// ═══════════════════════════════════════════════════════════════════

export async function generateDiagram(analysis, outputPath) {
  const html = buildHTML(analysis);
  writeFileSync(outputPath, html, "utf8");
}

function buildHTML(a) {
  const title = a.name || "Repository";
  const frameworkLabel = formatFramework(a.framework);
  const routeGroups = groupRoutes(a.routes);
  const apiGroups = groupAPIs(a.api);
  const agentsByTier = groupAgentsByTier(a.agents);
  const componentGroups = groupComponents(a.components);

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${title} — Architecture Map</title>
<style>${CSS}</style>
</head>
<body>
<div class="page">

<div class="header-row">
  <div>
    <h1>${title}</h1>
    <p class="subtitle">Architecture Map &mdash; generated by parc</p>
  </div>
  <div class="stats-row">
    ${statBadge(a.summary.totalFiles, "files")}
    ${statBadge(a.routes.length, "routes")}
    ${statBadge(a.api.length, "API endpoints")}
    ${statBadge(a.agents.length, "agents")}
    ${statBadge(a.components.length, "components")}
    ${a.database.tables.length ? statBadge(a.database.tables.length, "tables") : ""}
  </div>
</div>

<div class="meta-row">
  ${a.git.branch ? `<span class="meta-tag">${a.git.branch}</span>` : ""}
  <span class="meta-tag">${frameworkLabel}</span>
  ${a.summary.languages.map(l => `<span class="meta-tag">${l}</span>`).join("")}
  ${a.summary.features.map(f => `<span class="meta-tag g">${f}</span>`).join("")}
</div>

<div class="tabs">
  <div class="tab active" onclick="switchTab('overview')">Overview</div>
  ${a.routes.length ? '<div class="tab" onclick="switchTab(\'routes\')">Routes</div>' : ""}
  ${a.api.length ? '<div class="tab" onclick="switchTab(\'api\')">API</div>' : ""}
  ${a.agents.length ? '<div class="tab" onclick="switchTab(\'agents\')">Agents</div>' : ""}
  ${a.components.length ? '<div class="tab" onclick="switchTab(\'components\')">Components</div>' : ""}
  ${a.database.tables.length ? '<div class="tab" onclick="switchTab(\'data\')">Data</div>' : ""}
  <div class="tab" onclick="switchTab('git')">Git</div>
</div>

<!-- OVERVIEW TAB -->
<div id="tab-overview" class="tab-content active">
  <div class="arch-grid">
    ${a.routes.length ? `
    <div class="arch-box green">
      <div class="arch-label">Frontend</div>
      <div class="arch-title">${a.routes.length} Routes</div>
      <div class="arch-items">
        ${Object.entries(routeGroups).map(([group, routes]) =>
          `<span class="tag g">${group} (${routes.length})</span>`
        ).join("")}
      </div>
    </div>` : ""}

    ${a.api.length ? `
    <div class="arch-box amber">
      <div class="arch-label">API Layer</div>
      <div class="arch-title">${a.api.length} Endpoints</div>
      <div class="arch-items">
        ${Object.entries(apiGroups).map(([group, endpoints]) =>
          `<span class="tag a">${group} (${endpoints.length})</span>`
        ).join("")}
      </div>
    </div>` : ""}

    ${a.agents.length ? `
    <div class="arch-box amber">
      <div class="arch-label">AI Agents</div>
      <div class="arch-title">${a.agents.length} Agents</div>
      <div class="arch-items">
        ${a.agents.map(agent =>
          `<span class="tag a">${agent.name}</span>`
        ).join("")}
      </div>
    </div>` : ""}

    ${a.components.length ? `
    <div class="arch-box blue">
      <div class="arch-label">Components</div>
      <div class="arch-title">${a.components.length} Components</div>
      <div class="arch-items">
        ${Object.entries(componentGroups).map(([type, comps]) =>
          `<span class="tag b">${type} (${comps.length})</span>`
        ).join("")}
      </div>
    </div>` : ""}

    ${a.database.tables.length ? `
    <div class="arch-box blue">
      <div class="arch-label">Database</div>
      <div class="arch-title">${a.database.tables.length} Tables</div>
      <div class="arch-items">
        ${a.database.tables.map(t => `<span class="tag b">${t.name}</span>`).join("")}
      </div>
    </div>` : ""}

    ${a.packages.length > 1 ? `
    <div class="arch-box gray">
      <div class="arch-label">Packages</div>
      <div class="arch-title">${a.packages.length} Packages</div>
      <div class="arch-items">
        ${a.packages.map(p => `<span class="tag">${p.name} <small>(${p.path})</small></span>`).join("")}
      </div>
    </div>` : ""}
  </div>

  ${a.agents.length > 0 && a.api.length > 0 ? `
  <div class="section" style="margin-top:40px;">
    <div class="section-title">Data Flow</div>
    <div class="section-sub">How data moves through the system</div>
    <div class="flow-row">
      ${a.routes.length ? '<div class="flow-node green">Frontend Routes</div><div class="arrow-wrap"><div class="flow-arrow"></div></div>' : ""}
      ${a.api.length ? '<div class="flow-node amber">API Endpoints</div><div class="arrow-wrap"><div class="flow-arrow"></div></div>' : ""}
      ${a.agents.length ? '<div class="flow-node amber">AI Agents</div><div class="arrow-wrap"><div class="flow-arrow"></div></div>' : ""}
      ${a.database.tables.length ? '<div class="flow-node blue">Database</div>' : ""}
    </div>
  </div>` : ""}
</div>

<!-- ROUTES TAB -->
${a.routes.length ? `
<div id="tab-routes" class="tab-content">
  <table class="route-table">
    <thead><tr><th>Type</th><th>Path</th><th>File</th></tr></thead>
    <tbody>
      ${a.routes.map(r => `
        <tr>
          <td><span class="tag ${r.type === "static" ? "g" : "a"}">${r.type}</span></td>
          <td>${r.path}</td>
          <td class="file-path">${r.file}</td>
        </tr>
      `).join("")}
    </tbody>
  </table>
</div>` : ""}

<!-- API TAB -->
${a.api.length ? `
<div id="tab-api" class="tab-content">
  <table class="route-table">
    <thead><tr><th>Method</th><th>Path</th><th>Auth</th><th>File</th></tr></thead>
    <tbody>
      ${a.api.map(e => `
        <tr>
          <td>${e.methods.map(m => `<span class="tag ${m === "GET" ? "" : "g"}">${m}</span>`).join(" ")}</td>
          <td>${e.path}</td>
          <td>${e.auth ? '<span class="tag g">yes</span>' : '<span class="tag r">no</span>'}</td>
          <td class="file-path">${e.file}</td>
        </tr>
      `).join("")}
    </tbody>
  </table>
</div>` : ""}

<!-- AGENTS TAB -->
${a.agents.length ? `
<div id="tab-agents" class="tab-content">
  <div class="arch-grid">
    ${Object.entries(agentsByTier).map(([tier, agents]) => `
      <div class="arch-box amber" style="grid-column: 1 / -1;">
        <div class="arch-label">Tier: ${tier}</div>
        <div class="arch-title">${agents.length} Agents</div>
        <div class="agent-list">
          ${agents.map(agent => `
            <div class="agent-card">
              <div class="agent-name">${agent.name}</div>
              <div class="agent-file">${agent.file}</div>
              ${agent.description ? `<div class="agent-desc">${agent.description}</div>` : ""}
              <div class="arch-items" style="margin-top:6px;">
                ${agent.tools.map(t => `<span class="tag a">${t}</span>`).join("")}
              </div>
            </div>
          `).join("")}
        </div>
      </div>
    `).join("")}
  </div>
</div>` : ""}

<!-- COMPONENTS TAB -->
${a.components.length ? `
<div id="tab-components" class="tab-content">
  <div class="arch-grid">
    ${Object.entries(componentGroups).map(([type, comps]) => `
      <div class="arch-box blue">
        <div class="arch-label">${type}</div>
        <div class="arch-title">${comps.length} Components</div>
        <div class="arch-items">
          ${comps.map(c => `<span class="tag b">${c.name}</span>`).join("")}
        </div>
      </div>
    `).join("")}
  </div>
</div>` : ""}

<!-- DATA TAB -->
${a.database.tables.length ? `
<div id="tab-data" class="tab-content">
  <div class="arch-grid">
    <div class="arch-box blue" style="grid-column: 1 / -1;">
      <div class="arch-label">Database Tables</div>
      <div class="arch-title">${a.database.tables.length} Tables</div>
      <div class="arch-items">
        ${a.database.tables.map(t => `<span class="tag b">${t.name} <small>(${t.source})</small></span>`).join("")}
      </div>
    </div>
    ${a.database.migrations.length ? `
    <div class="arch-box gray" style="grid-column: 1 / -1;">
      <div class="arch-label">Migrations</div>
      <div class="arch-title">${a.database.migrations.length} Migrations</div>
      <div class="arch-items">
        ${a.database.migrations.map(m => `<span class="tag">${m.name}</span>`).join("")}
      </div>
    </div>` : ""}
  </div>
</div>` : ""}

<!-- GIT TAB -->
<div id="tab-git" class="tab-content">
  <div class="arch-grid">
    <div class="arch-box gray" style="grid-column: 1 / -1;">
      <div class="arch-label">Repository</div>
      <div class="arch-title">${title}</div>
      <div class="arch-desc">
        ${a.git.branch ? `<strong>Branch:</strong> ${a.git.branch}<br>` : ""}
        ${a.git.lastCommit ? `<strong>Last commit:</strong> ${a.git.lastCommit}<br>` : ""}
        ${a.git.lastAuthor ? `<strong>Author:</strong> ${a.git.lastAuthor}<br>` : ""}
        ${a.git.commitCount ? `<strong>Commits:</strong> ${a.git.commitCount}<br>` : ""}
        ${a.git.remoteUrl ? `<strong>Remote:</strong> ${a.git.remoteUrl}` : ""}
      </div>
    </div>
    <div class="arch-box gray">
      <div class="arch-label">File Breakdown</div>
      <div class="arch-title">${a.summary.totalFiles} Files</div>
      <div class="arch-items">
        ${Object.entries(a.summary.extensionCounts).sort((a,b) => b[1] - a[1]).map(([ext, count]) =>
          `<span class="tag">${ext} (${count})</span>`
        ).join("")}
      </div>
    </div>
    <div class="arch-box gray">
      <div class="arch-label">Configs</div>
      <div class="arch-title">${a.configs.length} Config Files</div>
      <div class="arch-items">
        ${a.configs.map(c => `<span class="tag">${c.path}</span>`).join("")}
      </div>
    </div>
    <div class="arch-box gray">
      <div class="arch-label">Dependencies</div>
      <div class="arch-title">${a.packages.reduce((sum, p) => sum + p.dependencies.length, 0)} packages</div>
      <div class="arch-items">
        ${a.packages.flatMap(p => p.dependencies).slice(0, 30).map(d =>
          `<span class="tag">${d}</span>`
        ).join("")}
        ${a.packages.flatMap(p => p.dependencies).length > 30 ? `<span class="tag">+${a.packages.flatMap(p => p.dependencies).length - 30} more</span>` : ""}
      </div>
    </div>
  </div>
</div>

<div class="footer">Generated by <strong>parc</strong> &mdash; ${new Date().toISOString().split("T")[0]}</div>

</div>
<script>
function switchTab(id) {
  document.querySelectorAll('.tab').forEach(t => t.classList.remove('active'));
  document.querySelectorAll('.tab-content').forEach(t => t.classList.remove('active'));
  document.getElementById('tab-' + id).classList.add('active');
  document.querySelector('[onclick="switchTab(\\'' + id + '\\')"]').classList.add('active');
}
</script>
</body>
</html>`;
}

// ─── Helpers ─────────────────────────────────────────────────────

function statBadge(count, label) {
  return `<div class="stat"><span class="stat-num">${count}</span><span class="stat-label">${label}</span></div>`;
}

function formatFramework(fw) {
  const names = {
    nextjs: "Next.js", nuxt: "Nuxt", sveltekit: "SvelteKit", astro: "Astro",
    "vite-react": "Vite + React", "vite-vue": "Vite + Vue",
    express: "Express", fastify: "Fastify", unknown: "Unknown",
  };
  return `${names[fw.name] || fw.name}${fw.version ? " " + fw.version : ""}`;
}

function groupRoutes(routes) {
  const groups = {};
  for (const r of routes) {
    const segment = r.path.split("/").filter(Boolean)[0] || "root";
    (groups[segment] = groups[segment] || []).push(r);
  }
  return groups;
}

function groupAPIs(endpoints) {
  const groups = {};
  for (const e of endpoints) {
    const parts = e.path.replace(/^\/api\//, "").split("/");
    const key = parts[0] || "root";
    (groups[key] = groups[key] || []).push(e);
  }
  return groups;
}

function groupAgentsByTier(agents) {
  const groups = {};
  for (const a of agents) {
    const tier = a.tier || "unknown";
    (groups[tier] = groups[tier] || []).push(a);
  }
  return groups;
}

function groupComponents(components) {
  const groups = {};
  for (const c of components) {
    (groups[c.type] = groups[c.type] || []).push(c);
  }
  return groups;
}

// ─── CSS ─────────────────────────────────────────────────────────

const CSS = `
@import url('https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;600;700&family=DM+Sans:wght@400;500;600&family=DM+Mono:wght@400;500&display=swap');

* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: 'DM Sans', system-ui, sans-serif; background: #FAFAF8; color: #111114; }
.page { max-width: 1400px; margin: 0 auto; padding: 48px 40px; }

h1 { font-family: 'Cormorant Garamond', serif; font-size: 2.6rem; font-weight: 700; margin-bottom: 4px; }
.subtitle { font-family: 'DM Mono', monospace; font-size: 0.7rem; text-transform: uppercase; letter-spacing: 0.12em; color: #888; }

.header-row { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 16px; }
.stats-row { display: flex; gap: 16px; }
.stat { text-align: center; }
.stat-num { display: block; font-family: 'Cormorant Garamond', serif; font-size: 1.4rem; font-weight: 700; color: #2A7A5B; }
.stat-label { font-family: 'DM Mono', monospace; font-size: 0.58rem; text-transform: uppercase; letter-spacing: 0.1em; color: #aaa; }

.meta-row { display: flex; flex-wrap: wrap; gap: 6px; margin-bottom: 32px; }
.meta-tag { font-family: 'DM Mono', monospace; font-size: 0.62rem; background: #F6F5F2; border: 1px solid #E8E5E0; border-radius: 4px; padding: 3px 8px; color: #555; }
.meta-tag.g { background: #E8F5EE; border-color: #2A7A5B33; color: #2A7A5B; }

.tabs { display: flex; gap: 0; margin-bottom: 32px; border-bottom: 1px solid #E8E5E0; }
.tab { padding: 10px 20px; font-family: 'DM Mono', monospace; font-size: 0.7rem; text-transform: uppercase; letter-spacing: 0.1em; color: #888; cursor: pointer; border-bottom: 2px solid transparent; transition: all 200ms; }
.tab:hover { color: #111114; }
.tab.active { color: #2A7A5B; border-bottom-color: #2A7A5B; }
.tab-content { display: none; }
.tab-content.active { display: block; }

.section { margin-bottom: 48px; }
.section-title { font-family: 'Cormorant Garamond', serif; font-size: 1.4rem; font-weight: 600; margin-bottom: 6px; }
.section-sub { font-family: 'DM Mono', monospace; font-size: 0.65rem; text-transform: uppercase; letter-spacing: 0.12em; color: #aaa; margin-bottom: 20px; }

.arch-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(320px, 1fr)); gap: 16px; }
.arch-box { background: #fff; border: 1px solid #E8E5E0; border-radius: 8px; padding: 20px; position: relative; overflow: hidden; }
.arch-box::before { content: ''; position: absolute; top: 0; left: 0; right: 0; height: 3px; background: var(--bar, #E8E5E0); }
.arch-box.green::before { --bar: #2A7A5B; }
.arch-box.amber::before { --bar: #B8860B; }
.arch-box.blue::before { --bar: #2980B9; }
.arch-box.gray::before { --bar: #888; }

.arch-label { font-family: 'DM Mono', monospace; font-size: 0.6rem; text-transform: uppercase; letter-spacing: 0.14em; color: #aaa; margin-bottom: 8px; }
.arch-title { font-family: 'Cormorant Garamond', serif; font-size: 1.15rem; font-weight: 600; margin-bottom: 10px; }
.arch-desc { font-size: 0.78rem; color: #666; line-height: 1.5; margin-bottom: 10px; }
.arch-items { display: flex; flex-wrap: wrap; gap: 5px; }

.tag { display: inline-block; font-family: 'DM Mono', monospace; font-size: 0.62rem; background: #F6F5F2; border: 1px solid #E8E5E0; border-radius: 4px; padding: 2px 8px; color: #555; }
.tag.g { background: #E8F5EE; border-color: #2A7A5B33; color: #2A7A5B; }
.tag.b { background: #EBF0FF; border-color: #2980B933; color: #2980B9; }
.tag.a { background: #FFF3E0; border-color: #B8860B33; color: #B8860B; }
.tag.r { background: #FDEDEC; border-color: #C0392B33; color: #C0392B; }
.tag.d { background: #111114; border-color: #111114; color: #fff; }
.tag small { opacity: 0.6; }

.agent-list { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 12px; margin-top: 12px; }
.agent-card { background: #FFFDF8; border: 1px solid #E8E5E0; border-radius: 6px; padding: 12px; }
.agent-name { font-family: 'DM Sans', sans-serif; font-size: 0.82rem; font-weight: 600; margin-bottom: 2px; }
.agent-file { font-family: 'DM Mono', monospace; font-size: 0.6rem; color: #aaa; margin-bottom: 4px; }
.agent-desc { font-size: 0.72rem; color: #666; }

.route-table { width: 100%; border-collapse: collapse; font-size: 0.78rem; }
.route-table th { font-family: 'DM Mono', monospace; font-size: 0.62rem; text-transform: uppercase; letter-spacing: 0.1em; color: #aaa; text-align: left; padding: 8px 12px; border-bottom: 1px solid #E8E5E0; }
.route-table td { padding: 8px 12px; border-bottom: 1px solid #F6F5F2; color: #444; }
.route-table tr:hover td { background: #F6F5F2; }
.file-path { font-family: 'DM Mono', monospace; font-size: 0.65rem; color: #aaa; }

.flow-row { display: flex; align-items: center; gap: 0; flex-wrap: wrap; margin-bottom: 16px; }
.flow-node { background: #fff; border: 1px solid #E8E5E0; border-radius: 8px; padding: 10px 16px; font-size: 0.78rem; font-weight: 500; white-space: nowrap; }
.flow-node.green { background: #2A7A5B; color: #fff; border-color: #2A7A5B; }
.flow-node.amber { background: #FFF3E0; color: #B8860B; border-color: #B8860B44; }
.flow-node.blue { background: #EBF0FF; color: #2980B9; border-color: #2980B944; }
.flow-arrow { width: 36px; height: 2px; background: #ccc; position: relative; flex-shrink: 0; }
.flow-arrow::after { content: ''; position: absolute; right: 0; top: -4px; border: 5px solid transparent; border-left: 6px solid #ccc; }
.arrow-wrap { position: relative; display: flex; align-items: center; flex-shrink: 0; }

.footer { margin-top: 64px; padding-top: 16px; border-top: 1px solid #E8E5E0; font-family: 'DM Mono', monospace; font-size: 0.62rem; color: #aaa; }
`;
